import { ArrowUpRight, RefreshCw } from "lucide-react";
import { useState } from "react";
import { Card } from "../components/Card";
import HistoricalChart from "../components/HistoricalChart";
import { useRates } from "../hooks/useRates";
const NEWS=[
 {flag:"🇰🇪",title:"Kenyan Shilling remains closely watched against the US Dollar",date:"Today",text:"Exchange-rate movement affects imported goods, travel budgets and international transfers."},
 {flag:"🇺🇸",title:"Inflation data expected to influence KES movement",date:"Yesterday",text:"Analysts continue to watch global rate expectations and their effect on emerging-market currencies."},
 {flag:"🇬🇧",title:"Global market update: Dollar strengthens",date:"2 days ago",text:"A stronger dollar can change the cost of international spending and remittances."}
];
export default function TrendsNews(){const {rates,status,reload}=useRates("KES");const [quote,setQuote]=useState("USD");return <div><div className="mb-4 flex items-end justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[.12em] text-slate-400">Market intelligence</p><h1 className="mt-1 text-[18px] font-bold">Historical Trends / News</h1></div><button onClick={reload} className="rounded-lg border border-slate-200 bg-white p-2 text-slate-500"><RefreshCw size={14} className={status==="loading"?"animate-spin":""}/></button></div><div className="grid gap-3 xl:grid-cols-[1.35fr_.85fr]"><Card className="p-5"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold">Historical Trends</p><p className="mt-1 text-[9px] text-slate-400">Live market context</p></div><select value={quote} onChange={e=>setQuote(e.target.value)} className="rounded-md border border-slate-200 px-2 py-2 text-[9px]"><option>USD</option><option>GBP</option><option>EUR</option><option>AED</option></select></div><div className="mt-4"><HistoricalChart base={quote} quote="EUR"/></div><div className="mt-3 grid grid-cols-3 gap-2"><div className="rounded-lg bg-slate-50 p-3"><p className="text-[8px] text-slate-400">Today</p><b className="mt-1 block text-sm">{rates?.[quote]?.toFixed(2)||"—"}</b></div><div className="rounded-lg bg-slate-50 p-3"><p className="text-[8px] text-slate-400">7 days</p><b className="mt-1 block text-sm text-[#43b34d]">+0.85%</b></div><div className="rounded-lg bg-slate-50 p-3"><p className="text-[8px] text-slate-400">30 days</p><b className="mt-1 block text-sm text-red-400">-1.40%</b></div></div></Card><Card className="overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><p className="text-[10px] font-bold">Financial News</p><p className="mt-1 text-[9px] text-slate-400">Short editorial context for your money decisions.</p></div><div>{NEWS.map(n=><article key={n.title} className="border-b border-slate-100 p-4 last:border-b-0"><div className="flex gap-3"><span className="text-lg">{n.flag}</span><div><div className="flex justify-between gap-4"><h3 className="text-[10px] font-bold leading-4">{n.title}</h3><span className="shrink-0 text-[8px] text-slate-400">{n.date}</span></div><p className="mt-1.5 text-[9px] leading-4 text-slate-500">{n.text}</p><button className="mt-2 flex items-center gap-1 text-[8px] font-semibold text-[#43b34d]">Read more <ArrowUpRight size={10}/></button></div></div></article>)}</div></Card></div></div>}
