"""add user avatar

Revision ID: 242f2eca9fbc
Revises: 13b8ffb6f741
Create Date: 2026-08-30 12:08:07.773246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '242f2eca9fbc'
down_revision = '13b8ffb6f741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
