"""add trips table

Revision ID: 87a03f8c9bf5
Revises: e337a7d28f55
Create Date: 2026-08-30 12:58:50.406728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87a03f8c9bf5'
down_revision = 'e337a7d28f55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('destination', sa.String(length=120), nullable=False),
    sa.Column('travel_date', sa.Date(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('budget_kes', sa.Float(), nullable=False),
    sa.Column('target_currency', sa.String(length=3), nullable=False),
    sa.Column('channel', sa.String(length=40), nullable=True),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('converted_amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trips_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trips_user_id'))

    op.drop_table('trips')
    # ### end Alembic commands ###
